apiVersion: v1
kind: Config

clusters:
- name: dev-cluster
  cluster:
    server: https://127.0.0.1:6443
    insecure-skip-tls-verify: true

users:
- name: jenkins
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImVhc2F2THo5dThxaXpKZFdSNl9NM2JCbVc4a3ZkZVRyOUZlZjUtUTNLcW8ifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzcwMTQ0NzEzLCJpYXQiOjE3Njk5NzE5MTMsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYjY0ZWExYTctNmQ3NC00YjQzLWEwMmMtNWYzNDEwNjFhNjQ5Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJqZW5raW5zIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImplbmtpbnMtZGVwbG95ZXIiLCJ1aWQiOiJjZDgxNmJlZi1hYTBiLTRjNzctYTk3Yy0zYjU4NTk1MzdmN2EifX0sIm5iZiI6MTc2OTk3MTkxMywic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmplbmtpbnM6amVua2lucy1kZXBsb3llciJ9.Qs88cNBldf7u0kMqpdJpp43j0K8z64gjZqoi2bm_zX3X4FIU_f5tFKYey_g6ArUWPisdyhp1cWHE7g3Cc6L89beFOjsK-kpeT2pkQk5xS6Z__US1wHIFD5tSsxms5HfwbMXePw68-VY68cscgHkskVv6-bAAoZj6d6Cfuvx8U3Mbi2DYKd2aiQmJlG6P9s86CK2rMTzs0Ln7Tu6w4l_QzeE5zkYgJk9kUwV9Zh_ziXGAga9q5nsY854aT7C1psG6EIUFIj3-ZZWYdW1v-ke9e6HTfvXb8MoFw68VeCR7fY2_GjO4WuibReWJGir39N_x6-uxth7sPH3bngseD-3JFg

contexts:
- name: jenkins
  context:
    cluster: dev-cluster
    user: jenkins
    namespace: dev

current-context: jenkins
