apiVersion: v1
kind: Config

clusters:
- name: dev-cluster
  cluster:
    server: https://127.0.0.1:6443
    insecure-skip-tls-verify: true

users:
- name: jenkins
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImVhc2F2THo5dThxaXpKZFdSNl9NM2JCbVc4a3ZkZVRyOUZlZjUtUTNLcW8ifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzY5ODE3NDAxLCJpYXQiOjE3Njk4MTM4MDEsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiNzY4MDY5ZDUtNWE4Yi00YjEyLTk4ZWYtMWY1ZTRkZDdiY2IxIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJqZW5raW5zIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImplbmtpbnMtZGVwbG95ZXIiLCJ1aWQiOiJjZDgxNmJlZi1hYTBiLTRjNzctYTk3Yy0zYjU4NTk1MzdmN2EifX0sIm5iZiI6MTc2OTgxMzgwMSwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmplbmtpbnM6amVua2lucy1kZXBsb3llciJ9.CD_rnBgGW8G0rgoV73i5gj_1XCk9DjoMUGF_40qQQF5j5j-VSlvrEuOfeAqRcL14nSRLnMwY5pmOAilNU6baJhhCK08dU7MSsl5YXGEZySsd7uP0OxVRL9sQte0V_my4kZ2wSDrFqa54jhLO89HXCla2c77R8-FhX4B2b4lQXGjPXgvHQP8Y804pbQmO06x_-ktc_jrJhBerVgpaeFC9guenQvpl1Mohl6w5uV_N4YMd09cucEQ4ogZGuNCrI3E4v7lElAzfGGZG1P6J_QuAb9btmu_UhpIIyxlChiA2KdXQZVbjEk_SR8xCTElec08IQaqeOYYRnPStritnNzgjgg

contexts:
- name: jenkins
  context:
    cluster: dev-cluster
    user: jenkins
    namespace: dev

current-context: jenkins
