apiVersion: v1
kind: Config

clusters:
- name: dev-cluster
  cluster:
    server: https://127.0.0.1:6443
    insecure-skip-tls-verify: true

users:
- name: jenkins
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImVhc2F2THo5dThxaXpKZFdSNl9NM2JCbVc4a3ZkZVRyOUZlZjUtUTNLcW8ifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzY5ODE2ODc4LCJpYXQiOjE3Njk4MTMyNzgsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiYTM0MWRmMzUtZDg5ZC00M2I4LWE3ODItYjU0MWIyNjMwMzg5Iiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJqZW5raW5zIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImplbmtpbnMtZGVwbG95ZXIiLCJ1aWQiOiJjZDgxNmJlZi1hYTBiLTRjNzctYTk3Yy0zYjU4NTk1MzdmN2EifX0sIm5iZiI6MTc2OTgxMzI3OCwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmplbmtpbnM6amVua2lucy1kZXBsb3llciJ9.St_YAx2Ic9f8tXz0GkeI5zQIIun3_TdbuyHsfdN8rXEInj1Lun-68X1MiPNkJeaod0NVewZGjwYfAtb4D6-UiWFTtg0xC2Vu0j_dg2cicsaj5YLo-_qrGwQO-RqhrZCSYW0rUCIuIXnYtYVLmktP-wKSFSeYUSwpGrjbMScaSMzzydicvp3iv5hfYWDcurYMrH4ZLZRdwkkQZCiAVkzDEMRBOkFlEF3VNU6SNOXZMi2kxp1P9JJp2gtwUGBnf3HqX-rvhVWPGJYoUayWcnmOagQ-1CtSlrpOOqcuELtzlKDV0jXNtZu_PrA6Vy8-ikJwViWXD7LU9M_gD0FQlw222g

contexts:
- name: jenkins
  context:
    cluster: dev-cluster
    user: jenkins
    namespace: dev

current-context: jenkins
