apiVersion: v1
kind: Config

clusters:
- name: dev-cluster
  cluster:
    server: https://127.0.0.1:6443
    insecure-skip-tls-verify: true

users:
- name: jenkins
  user:
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImVhc2F2THo5dThxaXpKZFdSNl9NM2JCbVc4a3ZkZVRyOUZlZjUtUTNLcW8ifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiLCJrM3MiXSwiZXhwIjoxNzY5NzgyODY2LCJpYXQiOjE3Njk3NzkyNjYsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiNmQxNDZlODgtMGNmNS00NjgwLWIzZTYtNjljNzRkMTlhYmVjIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJqZW5raW5zIiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImplbmtpbnMiLCJ1aWQiOiJlNzRmNGVhNC04MDhmLTQxYjEtOWJiYi1hZGYyNjZlOTk4NTMifX0sIm5iZiI6MTc2OTc3OTI2Niwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmplbmtpbnM6amVua2lucyJ9.qosWyWShHg21RLE-L0EnN_Y9IE4lgUrxoR3gzTZWJ9_0lFy4o4wU23VmZ2SekMtGmpbYHjsJxRFZzHUe0Jik2XuqmOflE5qyRCZ-dlVuT_N4jmOioYumR1L9XDysa08RAwJCB7Fz1BC6_z5DqNSKXV7Z3uyM1Q9Oesw7cGEBBDW78Gu6viOaoQLHDlVj4itrzwlV5TO5XfhPpt4-qANfdIR-csfrjB4jxi6oWXCJG75QoU0mkrxrKV_uoUyONpXmSX_3mK9EYdA59I508RNJEaCwnDcXVTbzoN25L-njfhpEHnE8jCYRYOvJZSgCjxGlOAkbpVoaOX5hc0BXEDxXvw

contexts:
- name: jenkins
  context:
    cluster: dev-cluster
    user: jenkins
    namespace: dev

current-context: jenkins
